.data
ChrLower	db 000h
	db 001h
	db 002h
	db 003h
	db 004h
	db 005h
	db 006h
	db 007h
	db 008h
	db 009h
	db 00Ah
	db 00Bh
	db 00Ch
	db 00Dh
	db 00Eh
	db 00Fh
	db 010h
	db 011h
	db 012h
	db 013h
	db 014h
	db 015h
	db 016h
	db 017h
	db 018h
	db 019h
	db 01Ah
	db 01Bh
	db 01Ch
	db 01Dh
	db 01Eh
	db 01Fh
	db 020h
	db 021h
	db 022h
	db 023h
	db 024h
	db 025h
	db 026h
	db 027h
	db 028h
	db 029h
	db 02Ah
	db 02Bh
	db 02Ch
	db 02Dh
	db 02Eh
	db 02Fh
	db 030h	; 0
	db 031h	; 1
	db 032h	; 2
	db 033h	; 3
	db 034h	; 4
	db 035h	; 5
	db 036h	; 6
	db 037h	; 7
	db 038h	; 8
	db 039h	; 9
	db 03Ah
	db 03Bh
	db 03Ch
	db 03Dh
	db 03Eh
	db 03Fh
	db 040h
	db 061h	; a
	db 062h	; b
	db 063h	; c
	db 064h	; d
	db 065h	; e
	db 066h	; f
	db 067h	; g
	db 068h	; h
	db 069h	; i
	db 06Ah	; j
	db 06Bh	; k
	db 06Ch	; l
	db 06Dh	; m
	db 06Eh	; n
	db 06Fh	; o
	db 070h	; p
	db 071h	; q
	db 072h	; r
	db 073h	; s
	db 074h	; t
	db 075h	; u
	db 076h	; v
	db 077h	; w
	db 078h	; x
	db 079h	; y
	db 07Ah	; z
	db 05Bh
	db 05Ch
	db 05Dh
	db 05Eh
	db 05Fh
	db 060h
	db 061h	; a
	db 062h	; b
	db 063h	; c
	db 064h	; d
	db 065h	; e
	db 066h	; f
	db 067h	; g
	db 068h	; h
	db 069h	; i
	db 06Ah	; j
	db 06Bh	; k
	db 06Ch	; l
	db 06Dh	; m
	db 06Eh	; n
	db 06Fh	; o
	db 070h	; p
	db 071h	; q
	db 072h	; r
	db 073h	; s
	db 074h	; t
	db 075h	; u
	db 076h	; v
	db 077h	; w
	db 078h	; x
	db 079h	; y
	db 07Ah	; z
	db 07Bh
	db 07Ch
	db 07Dh
	db 07Eh
	db 07Fh
	db 090h	; ê
	db 083h	; É
	db 082h
	db 083h	; É
	db 084h
	db 085h
	db 086h
	db 087h
	db 088h
	db 089h
	db 09Ah	; ö
	db 08Bh
	db 09Ch	; ú
	db 09Dh	; ù
	db 09Eh	; û
	db 09Fh	; ü
	db 090h	; ê
	db 091h
	db 092h
	db 093h
	db 094h
	db 095h
	db 096h
	db 097h
	db 098h
	db 099h
	db 09Ah	; ö
	db 09Bh
	db 09Ch	; ú
	db 09Dh	; ù
	db 09Eh	; û
	db 09Fh	; ü
	db 0A0h
	db 0A2h	; ¢
	db 0A2h	; ¢
	db 0BCh	; º
	db 0A4h
	db 0B4h	; ¥
	db 0A6h
	db 0A7h
	db 0B8h	; ∏
	db 0A9h
	db 0BAh	; ∫
	db 0ABh
	db 0ACh
	db 0ADh
	db 0AEh
	db 0BFh	; ø
	db 0B0h
	db 0B1h
	db 0B3h	; ≥
	db 0B3h	; ≥
	db 0B4h	; ¥
	db 0B5h	; µ
	db 0B6h
	db 0B7h
	db 0B8h	; ∏
	db 0B9h
	db 0BAh	; ∫
	db 0BBh
	db 0BCh	; º
	db 0BEh	; æ
	db 0BEh	; æ
	db 0BFh	; ø
	db 0E0h	; ‡
	db 0E1h	; ·
	db 0E2h	; ‚
	db 0E3h	; „
	db 0E4h	; ‰
	db 0E5h	; Â
	db 0E6h	; Ê
	db 0E7h	; Á
	db 0E8h	; Ë
	db 0E9h	; È
	db 0EAh	; Í
	db 0EBh	; Î
	db 0ECh	; Ï
	db 0EDh	; Ì
	db 0EEh	; Ó
	db 0EFh	; Ô
	db 0F0h	; 
	db 0F1h	; Ò
	db 0F2h	; Ú
	db 0F3h	; Û
	db 0F4h	; Ù
	db 0F5h	; ı
	db 0F6h	; ˆ
	db 0F7h	; ˜
	db 0F8h	; ¯
	db 0F9h	; ˘
	db 0FAh	; ˙
	db 0FBh	; ˚
	db 0FCh	; ¸
	db 0FDh	; ˝
	db 0FEh	; ˛
	db 0FFh	; ˇ
	db 0E0h	; ‡
	db 0E1h	; ·
	db 0E2h	; ‚
	db 0E3h	; „
	db 0E4h	; ‰
	db 0E5h	; Â
	db 0E6h	; Ê
	db 0E7h	; Á
	db 0E8h	; Ë
	db 0E9h	; È
	db 0EAh	; Í
	db 0EBh	; Î
	db 0ECh	; Ï
	db 0EDh	; Ì
	db 0EEh	; Ó
	db 0EFh	; Ô
	db 0F0h	; 
	db 0F1h	; Ò
	db 0F2h	; Ú
	db 0F3h	; Û
	db 0F4h	; Ù
	db 0F5h	; ı
	db 0F6h	; ˆ
	db 0F7h	; ˜
	db 0F8h	; ¯
	db 0F9h	; ˘
	db 0FAh	; ˙
	db 0FBh	; ˚
	db 0FCh	; ¸
	db 0FDh	; ˝
	db 0FEh	; ˛
	db 0FFh	; ˇ

CmpChrI macro
	xlatb
	xchg	eax, edx
	xlatb
	cmp	al, dl
	jne	NoMatch
	or	al, dl
	jz	StrEnd
	inc	ecx
endm
.code
comment *

	Returns 0 if strings are equal
	in other case returns 1-based index of first unmatched char

*
StrCmpi proc uses esi edi ebx pStr1:PBYTE, pStr2:PBYTE
	mov	ebx, offset ChrLower
	mov	esi, pStr1
	mov	edi, pStr2
	xor	ecx, ecx
	inc	ecx
MainLoop:	mov	eax, [esi]
	mov	edx, [edi]
	
	CmpChrI
	mov	al, ah
	mov	dl, dh
	
	CmpChrI
	shr	eax, 16
	shr	edx, 16
	
	CmpChrI
	mov	al, ah
	mov	dl, dh
	
	CmpChrI
	
	add	esi, 4
	add	edi, 4
	jmp	MainLoop
StrEnd:	xor	ecx, ecx
NoMatch:	mov	eax, ecx
	ret
StrCmpi endp 



